name = "TimeThis"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2024, John S. Urban"
[build]
   auto-executables = true
   auto-tests = true
   auto-examples = true
   module-naming = false
[install]
   library = false
[fortran]
   implicit-typing = false
   implicit-external = false
   source-form = "free"
[dependencies]
   M_time   = { git = "https://github.com/urbanjost/M_time.git" }
   #M_time  = { namespace = "GPF" }
   #M_time  = { path = "GLINKS/M_time" }

